# Generated by Django 3.2.17 on 2026-06-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_votingsnapshotasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingsnapshot',
            name='whitelisted_for_rewards',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
